### ISSUE TITLE
Remove pytest from run dependencies

### ISSUE THREAD

**Issue by gsakkis** [conda-forge/fastparquet-feedstock#25]
Currently conda installs pytest as a dependency of fastparquet, which shouldn't be the case.

**Comment by martindurant** [comment]
Agreed, pytest should not be a runtime dependency. Would you like to make a PR?

**Comment by gsakkis** [comment]
I could, though it would probably take you much less time as I haven't written/modified a conda recipe before. Is it just removing [this line](https://github.com/conda-forge/fastparquet-feedstock/blob/master/recipe/meta.yaml#L44) or the `pytest-runner` references too? Anything else that needs to change (e.g. version)?

**Comment by martindurant** [comment]
Removing that line should be all
