### ISSUE TITLE
Update to 0.8.1

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/fastparquet-feedstock#53]
Looks like the last release here is 0.8.0, but 0.8.1 is out. Would be good to upgrade.

Should add was about to start a PR, but noticed the `sdist` isn't on PyPI ( https://github.com/dask/fastparquet/issues/781 ). This may also be why the bot hasn't submitted an update PR.

**Comment by martindurant** [comment]
D'oh. I'll fix when I have a moment.

**Comment by jakirkham** [comment]
No worries. Thanks Martin 🙂

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/conda-forge/fastparquet-feedstock/pull/54 )
