### ISSUE TITLE
Issue with pip check when packaging fastparquet

### ISSUE THREAD

**Issue by xoolive** [conda-forge/fastparquet-feedstock#60]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I have a dependency on fastparquet on my recipe https://github.com/conda-forge/traffic-feedstock/ and the pip check command fails as it sees version 0.0.0 (conflicting with defined versions)

See the [problematic PR](https://github.com/conda-forge/traffic-feedstock/pull/10#issuecomment-1372703001)

### Installed packages

```shell
see PR attached
```

### Environment info

```shell
see PR attached
```

**Comment by BastianZim** [comment]
This needs to be added to the dependencies: https://github.com/dask/fastparquet/blob/72419dd3165708328e692512b9186c017eaade51/setup.py#L58 
That should do the trick but double check the logs if it's actually working, there might need to be an env variable set as well.

**Comment by BastianZim** [comment]
Yes the meta.yaml needs to be synced with upstream. Then it should correctly be reported.

**Comment by martindurant** [comment]
#61 - looks OK?
